

POST http://localhost:5000/api/v1/auth/send-verification-email HTTP/1.1
content-type: application/json

{
    "email":"*@gmail.com"
}

# mention an email which is prensent in data would recive verification mail